# Generated by Django 3.0.2 on 2020-05-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bombinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('addr', models.CharField(max_length=256)),
                ('casualties', models.CharField(max_length=256)),
                ('visible', models.IntegerField()),
                ('audit', models.IntegerField(default=0)),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'bombinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategoryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('tb', models.CharField(max_length=256, null=True)),
                ('tbid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('visible', models.IntegerField()),
                ('type', models.IntegerField()),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'categorytable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CheckTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stb', models.CharField(max_length=256, null=True)),
                ('sid', models.IntegerField(null=True)),
                ('tid', models.IntegerField(null=True)),
                ('audit', models.IntegerField(default=0)),
                ('method', models.IntegerField()),
                ('account', models.CharField(max_length=20, null=True)),
                ('content', models.TextField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'checktable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImgTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=256, null=True)),
                ('paths', models.CharField(max_length=256, null=True)),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'imgtable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RelationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit', models.IntegerField(default=0)),
                ('stb', models.CharField(max_length=256, null=True)),
                ('sid', models.IntegerField(null=True)),
                ('content', models.TextField(null=True)),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'relationtable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Simplelib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('zhname', models.CharField(max_length=256)),
                ('enname', models.CharField(max_length=256, null=True)),
                ('linkable', models.IntegerField()),
                ('nickname', models.CharField(max_length=256, null=True)),
                ('cas', models.CharField(max_length=256, null=True)),
                ('formula', models.CharField(max_length=256, null=True)),
                ('formulaWeight', models.CharField(max_length=256, null=True)),
                ('OxygenBalance', models.CharField(max_length=256, null=True)),
                ('nitrogen', models.CharField(max_length=256, null=True)),
                ('relativeDensity', models.CharField(max_length=256, null=True)),
                ('meltingPoint', models.CharField(max_length=256, null=True)),
                ('boilingPoint', models.CharField(max_length=256, null=True)),
                ('flashPoint', models.CharField(max_length=256, null=True)),
                ('decompTemp', models.CharField(max_length=256, null=True)),
                ('standardHeat', models.CharField(max_length=256, null=True)),
                ('heatCapacity', models.CharField(max_length=256, null=True)),
                ('character', models.TextField(null=True)),
                ('standardmg', models.CharField(max_length=256, null=True)),
                ('wettability', models.CharField(max_length=256, null=True)),
                ('combustionheat', models.CharField(max_length=256, null=True)),
                ('burstspeed', models.CharField(max_length=256, null=True)),
                ('temp', models.CharField(max_length=256, null=True)),
                ('bursthot', models.CharField(max_length=256, null=True)),
                ('burstpress', models.CharField(max_length=256, null=True)),
                ('burstvol', models.CharField(max_length=256, null=True)),
                ('burstpoint', models.CharField(max_length=256, null=True)),
                ('frisen', models.TextField(null=True)),
                ('impsen', models.TextField(null=True)),
                ('stasen', models.TextField(null=True)),
                ('explosionlimit', models.TextField(null=True)),
                ('svp', models.CharField(max_length=256, null=True)),
                ('img', models.CharField(max_length=256, null=True)),
                ('visible', models.IntegerField()),
                ('audit', models.IntegerField(default=0)),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'simplelib',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('account', models.CharField(max_length=256)),
                ('pwd', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('visible', models.IntegerField()),
                ('audit', models.IntegerField()),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'usertable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VersionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tb_name', models.CharField(max_length=256)),
                ('max_version', models.IntegerField()),
            ],
            options={
                'db_table': 'versiontable',
                'managed': True,
            },
        ),
    ]
