# Generated by Django 3.0.2 on 2020-05-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BombApp', '0002_bombinfo_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bombinfo',
            old_name='case',
            new_name='casename',
        ),
    ]
